---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
  - name: octavia-ca-passphrase
    literals:
      - server-ca-passphrase=12345678
    options:
      disableNameSuffixHash: true

resources:
  - externalapi.yaml
  - octavia_netattach.yaml

transformers:
  # Set namespace to OpenStack on all namespaced objects without a namespace
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: _ignored_
      namespace: openstack
    setRoleBindingSubjects: none
    unsetOnly: true
    fieldSpecs:
      - path: metadata/name
        kind: Namespace
        create: true

components:
  - ../../../../lib/networking/metallb
  - ../../../../lib/networking/netconfig
  - ../../../../lib/networking/nad

patches:
  - target:
      kind: NetworkAttachmentDefinition
      name: datacentre
    patch: |-
      apiVersion: k8s.cni.cncf.io/v1
      kind: NetworkAttachmentDefinition
      metadata:
        name: datacentre
      $patch: delete

replacements:
  # Add external interface and loadbalancer addresses
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.external.iface
    targets:
      - select:
          group: metallb.io
          kind: L2Advertisement
          name: external
        fieldPaths:
          - spec.interfaces.0
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.external.lb_addresses
    targets:
      - select:
          kind: IPAddressPool
          name: external
        fieldPaths:
          - spec.addresses

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.external.net-attach-def
    targets:
      - select:
          kind: NetworkAttachmentDefinition
          name: external
        fieldPaths:
          - spec.config

  # Replace ctlplane interfacename instead of bridge name.
  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.ctlplane.iface
    targets:
      - select:
          kind: L2Advertisement
          name: ctlplane
        fieldPaths:
          - spec.interfaces.0

  - source:
      kind: ConfigMap
      name: network-values
      fieldPath: data.octavia.net-attach-def
    targets:
      - select:
          kind: NetworkAttachmentDefinition
          name: octavia
        fieldPaths:
          - spec.config
