apiVersion: v1
data:
  AdminPassword: MTIzNDU2Nzg=
  AodhDatabasePassword: MTIzNDU2Nzg=
  AodhPassword: MTIzNDU2Nzg=
  BarbicanDatabasePassword: MTIzNDU2Nzg=
  BarbicanPassword: MTIzNDU2Nzg=
  CeilometerPassword: MTIzNDU2Nzg=
  CinderDatabasePassword: MTIzNDU2Nzg=
  CinderPassword: MTIzNDU2Nzg=
  DatabasePassword: MTIzNDU2Nzg=
  DbRootPassword: MTIzNDU2Nzg=
  DesignateDatabasePassword: MTIzNDU2Nzg=
  DesignatePassword: MTIzNDU2Nzg=
  GlanceDatabasePassword: MTIzNDU2Nzg=
  GlancePassword: MTIzNDU2Nzg=
  HeatAuthEncryptionKey: NzY3YzNlZDA1NmNiYWEzYjlkZmVkYjhjNmY4MjViZjA=
  HeatDatabasePassword: MTIzNDU2Nzg=
  HeatPassword: MTIzNDU2Nzg=
  IronicDatabasePassword: MTIzNDU2Nzg=
  IronicInspectorDatabasePassword: MTIzNDU2Nzg=
  IronicInspectorPassword: MTIzNDU2Nzg=
  IronicPassword: MTIzNDU2Nzg=
  KeystoneDatabasePassword: MTIzNDU2Nzg=
  ManilaDatabasePassword: MTIzNDU2Nzg=
  ManilaPassword: MTIzNDU2Nzg=
  MetadataSecret: MTIzNDU2Nzg0Mg==
  NeutronDatabasePassword: MTIzNDU2Nzg=
  NeutronPassword: MTIzNDU2Nzg=
  NovaAPIDatabasePassword: MTIzNDU2Nzg=
  NovaCell0DatabasePassword: MTIzNDU2Nzg=
  NovaCell1DatabasePassword: MTIzNDU2Nzg=
  NovaPassword: MTIzNDU2Nzg=
  OctaviaDatabasePassword: MTIzNDU2Nzg=
  OctaviaHeartbeatKey: MTIzNDU2Nzg=
  OctaviaPassword: MTIzNDU2Nzg=
  PlacementDatabasePassword: MTIzNDU2Nzg=
  PlacementPassword: MTIzNDU2Nzg=
  SwiftPassword: MTIzNDU2Nzg=
kind: Secret
metadata:
  name: osp-secret
  namespace: openstack
type: Opaque
---
apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: controlplane
  namespace: openstack
spec:
  barbican:
    apiOverride:
      route: {}
    template:
      barbicanAPI:
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
        replicas: 3
      barbicanKeystoneListener:
        replicas: 1
      barbicanWorker:
        replicas: 3
      databaseInstance: openstack
      preserveJobs: false
      secret: osp-secret
  ceilometer:
    template:
      passwordSelector:
        service: CeilometerPassword
      secret: osp-secret
      serviceUser: ceilometer
  cinder:
    apiOverride:
      route:
        haproxy.router.openshift.io/timeout: 60s
    template:
      cinderAPI:
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
        replicas: 3
      cinderBackup:
        networkAttachments:
        - storage
        replicas: 0
      cinderScheduler:
        replicas: 1
      cinderVolumes: {}
      customServiceConfig: |
        # Debug logs by default, jobs can override as needed.
        [DEFAULT]
        debug = true
      databaseInstance: openstack
      preserveJobs: false
      secret: osp-secret
    uniquePodNames: true
  designate:
    template:
      preserveJobs: false
  dns:
    template:
      options:
      - key: server
        values:
        - 192.168.122.1
      override:
        service:
          metadata:
            annotations:
              metallb.universe.tf/address-pool: ctlplane
              metallb.universe.tf/allow-shared-ip: ctlplane
              metallb.universe.tf/loadBalancerIPs: 192.168.122.80
          spec:
            type: LoadBalancer
      replicas: 2
  galera:
    enabled: true
    templates:
      openstack:
        replicas: 3
        secret: osp-secret
        storageRequest: 5G
      openstack-cell1:
        replicas: 3
        secret: osp-secret
        storageRequest: 5G
  glance:
    apiOverrides:
      default:
        route:
          haproxy.router.openshift.io/timeout: 60s
    template:
      customServiceConfig: |
        [DEFAULT]
        enabled_backends = default_backend:swift
        [glance_store]
        default_backend = default_backend
        [default_backend]
        swift_store_create_container_on_put = True
        swift_store_auth_version = 3
        swift_store_auth_address = {{ .KeystoneInternalURL }}
        swift_store_endpoint_type = internalURL
        swift_store_user = service:glance
        swift_store_key = {{ .ServicePassword }}
      databaseInstance: openstack
      glanceAPIs:
        default:
          networkAttachments:
          - storage
          override:
            service:
              internal:
                metadata:
                  annotations:
                    metallb.universe.tf/address-pool: internalapi
                    metallb.universe.tf/allow-shared-ip: internalapi
                    metallb.universe.tf/loadBalancerIPs: 172.17.0.80
                spec:
                  type: LoadBalancer
          replicas: 1
      preserveJobs: false
      storage:
        storageClass: local-storage
        storageRequest: 10G
    uniquePodNames: true
  heat:
    apiOverride:
      route: {}
    cnfAPIOverride:
      route: {}
    enabled: false
    template:
      databaseInstance: openstack
      heatAPI:
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
        replicas: 1
      heatEngine:
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
        replicas: 1
      preserveJobs: false
      secret: osp-secret
  horizon:
    apiOverride:
      route: {}
    enabled: true
    template:
      preserveJobs: false
      replicas: 1
      secret: osp-secret
  ironic:
    enabled: false
    template:
      databaseInstance: openstack
      ironicAPI:
        replicas: 1
      ironicConductors:
      - replicas: 1
        storageRequest: 10G
      ironicInspector:
        preserveJobs: false
        replicas: 1
      ironicNeutronAgent:
        replicas: 1
      preserveJobs: false
      secret: osp-secret
  keystone:
    apiOverride:
      route: {}
    template:
      databaseInstance: openstack
      override:
        service:
          internal:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.80
            spec:
              type: LoadBalancer
      preserveJobs: false
      replicas: 3
      secret: osp-secret
  manila:
    apiOverride:
      route:
        haproxy.router.openshift.io/timeout: 60s
    enabled: false
    template:
      manilaAPI:
        networkAttachments:
        - internalapi
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
        replicas: 1
      manilaScheduler:
        replicas: 1
      manilaShares:
        share1:
          networkAttachments:
          - storage
          replicas: 1
      preserveJobs: false
  memcached:
    templates:
      memcached:
        replicas: 3
  neutron:
    apiOverride:
      route: {}
    template:
      customServiceConfig: |
        [DEFAULT]
        global_physnet_mtu = 9000
        [ml2]
        mechanism_drivers = ovn
        [ovn]
        vhost_sock_dir = /var/lib/vhost_sockets
        [ml2_type_vlan]
        network_vlan_ranges = dpdk1:206:209,dpdk2:206:209 # CHANGEME
      databaseInstance: openstack
      networkAttachments:
      - internalapi
      override:
        service:
          internal:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.80
            spec:
              type: LoadBalancer
      preserveJobs: false
      replicas: 3
      secret: osp-secret
  nova:
    apiOverride:
      route: {}
    template:
      apiServiceTemplate:
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
        replicas: 3
      cellTemplates:
        cell0:
          cellDatabaseAccount: nova-cell0
          cellDatabaseInstance: openstack
          cellMessageBusInstance: rabbitmq
          conductorServiceTemplate:
            replicas: 1
          hasAPIAccess: true
        cell1:
          cellDatabaseAccount: nova-cell1
          cellDatabaseInstance: openstack-cell1
          cellMessageBusInstance: rabbitmq-cell1
          conductorServiceTemplate:
            replicas: 1
          hasAPIAccess: true
      metadataServiceTemplate:
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.80
            spec:
              type: LoadBalancer
        replicas: 3
      preserveJobs: false
      schedulerServiceTemplate:
        customServiceConfig: |
          [filter_scheduler]
          enabled_filtes = AvailabilityZoneFilter,ComputeFilter,ComputeCapabilitiesFilter,ImagePropertiesFilter,ServerGroupAntiAffinityFilter,ServerGroupAffinityFilter,PciPassthroughFilter,NUMATopologyFilter,AggregateInstanceExtraSpecsFilter
        replicas: 3
      secret: osp-secret
  octavia:
    enabled: false
    template:
      databaseInstance: openstack
      octaviaAPI:
        preserveJobs: false
        replicas: 1
      octaviaHealthManager: {}
      octaviaHousekeeping: {}
      octaviaWorker: {}
      preserveJobs: false
      secret: osp-secret
  ovn:
    template:
      ovnController:
        networkAttachment: tenant
        nicMappings:
          datacentre: ospbr
      ovnDBCluster:
        ovndbcluster-nb:
          dbType: NB
          networkAttachment: internalapi
          replicas: 3
          storageRequest: 10G
        ovndbcluster-sb:
          dbType: SB
          networkAttachment: internalapi
          replicas: 3
          storageRequest: 10G
      ovnNorthd:
        logLevel: info
        nThreads: 1
        replicas: 1
        resources: {}
        tls: {}
  placement:
    apiOverride:
      route: {}
    template:
      databaseInstance: openstack
      override:
        service:
          internal:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/allow-shared-ip: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.80
            spec:
              type: LoadBalancer
      preserveJobs: false
      replicas: 3
      secret: osp-secret
  rabbitmq:
    templates:
      rabbitmq:
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.85
            spec:
              type: LoadBalancer
        replicas: 3
      rabbitmq-cell1:
        override:
          service:
            metadata:
              annotations:
                metallb.universe.tf/address-pool: internalapi
                metallb.universe.tf/loadBalancerIPs: 172.17.0.86
            spec:
              type: LoadBalancer
        replicas: 3
  secret: osp-secret
  storageClass: local-storage
  swift:
    enabled: true
    proxyOverride:
      route: {}
    template:
      swiftProxy:
        override:
          service:
            internal:
              metadata:
                annotations:
                  metallb.universe.tf/address-pool: internalapi
                  metallb.universe.tf/allow-shared-ip: internalapi
                  metallb.universe.tf/loadBalancerIPs: 172.17.0.80
              spec:
                type: LoadBalancer
        replicas: 1
      swiftRing:
        ringReplicas: 1
      swiftStorage:
        replicas: 1
  telemetry:
    enabled: true
    template:
      autoscaling:
        aodh:
          databaseInstance: openstack
          memcachedInstance: memcached
          passwordSelectors: null
          preserveJobs: false
          secret: osp-secret
        enabled: false
        heatInstance: heat
      ceilometer:
        enabled: true
        secret: osp-secret
      logging:
        enabled: false
        port: 10514
      metricStorage:
        enabled: false
        monitoringStack:
          alertingEnabled: true
          scrapeInterval: 30s
          storage:
            persistent:
              pvcStorageClass: local-storage
              pvcStorageRequest: 10Gi
            retention: 24h
            strategy: persistent
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  labels:
    osp/net: ctlplane
    osp/net-attach-def-type: standard
  name: ctlplane
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "ctlplane",
      "type": "macvlan",
      "master": "ospbr",
      "ipam": {
        "type": "whereabouts",
        "range": "192.168.122.0/24",
        "range_start": "192.168.122.30",
        "range_end": "192.168.122.70"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  labels:
    osp/net: datacentre
    osp/net-attach-def-type: standard
  name: datacentre
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "datacentre",
      "type": "bridge",
      "bridge": "ospbr",
      "ipam": {}
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  labels:
    osp/net: internalapi
    osp/net-attach-def-type: standard
  name: internalapi
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "internalapi",
      "type": "macvlan",
      "master": "internalapi",
      "ipam": {
        "type": "whereabouts",
        "range": "172.17.0.0/24",
        "range_start": "172.17.0.30",
        "range_end": "172.17.0.70"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  labels:
    osp/net: storage
    osp/net-attach-def-type: standard
  name: storage
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "storage",
      "type": "macvlan",
      "master": "storage",
      "ipam": {
        "type": "whereabouts",
        "range": "172.20.0.0/24",
        "range_start": "172.20.0.30",
        "range_end": "172.20.0.70"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  labels:
    osp/net: tenant
    osp/net-attach-def-type: standard
  name: tenant
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "tenant",
      "type": "macvlan",
      "master": "tenant",
      "ipam": {
        "type": "whereabouts",
        "range": "172.18.0.0/24",
        "range_start": "172.18.0.30",
        "range_end": "172.18.0.70"
      }
    }
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  labels:
    osp/lb-addresses-type: standard
  name: external
  namespace: metallb-system
spec:
  addresses:
  - 172.19.0.80-172.19.0.90
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  labels:
    osp/lb-addresses-type: standard
  name: internalapi
  namespace: metallb-system
spec:
  addresses:
  - 172.17.0.80-172.17.0.90
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  labels:
    osp/lb-addresses-type: standard
  name: storage
  namespace: metallb-system
spec:
  addresses:
  - 172.20.0.80-172.20.0.90
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  labels:
    osp/lb-addresses-type: standard
  name: tenant
  namespace: metallb-system
spec:
  addresses:
  - 172.18.0.80-172.18.0.90
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: external
  namespace: metallb-system
spec:
  interfaces:
  - enp7s0.20
  ipAddressPools:
  - external
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: internalapi
  namespace: metallb-system
spec:
  interfaces:
  - enp7s0.20
  ipAddressPools:
  - internalapi
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: storage
  namespace: metallb-system
spec:
  interfaces:
  - enp7s0.21
  ipAddressPools:
  - storage
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: tenant
  namespace: metallb-system
spec:
  interfaces:
  - enp7s0.22
  ipAddressPools:
  - tenant
---
apiVersion: network.openstack.org/v1beta1
kind: NetConfig
metadata:
  name: netconfig
  namespace: openstack
spec:
  networks:
  - dnsDomain: ctlplane.example.com
    mtu: 9000
    name: ctlplane
    subnets:
    - allocationRanges:
      - end: 192.168.122.120
        start: 192.168.122.100
      - end: 192.168.122.200
        start: 192.168.122.150
      cidr: 192.168.122.0/24
      gateway: 192.168.122.1
      name: subnet1
  - dnsDomain: internalapi.example.com
    mtu: 1500
    name: internalapi
    subnets:
    - allocationRanges:
      - end: 172.17.0.250
        start: 172.17.0.100
      cidr: 172.17.0.0/24
      name: subnet1
      vlan: 17
  - dnsDomain: externalapi.example.com
    mtu: 1500
    name: external
    subnets:
    - allocationRanges:
      - end: 172.19.0.250
        start: 172.19.0.100
      cidr: 172.19.0.0/24
      name: subnet1
      vlan: 19
  - dnsDomain: storage.example.com
    mtu: 1500
    name: storage
    subnets:
    - allocationRanges:
      - end: 172.20.0.250
        start: 172.20.0.100
      cidr: 172.20.0.0/24
      name: subnet1
      vlan: 20
  - dnsDomain: tenant.example.com
    mtu: 1500
    name: tenant
    subnets:
    - allocationRanges:
      - end: 172.18.0.250
        start: 172.18.0.100
      cidr: 172.18.0.0/24
      name: subnet1
      vlan: 18
